project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files: [
  {
    source: "locale/messages.xlf",
    translation: "/locale/%two_letters_code%/%original_file_name%"
  },
  {
    source: "locale/messages.xlf",
    translation: "/locale/%two_letters_code%/%original_file_name%"
  }
]

