"project_id": CROWDIN_PROJECT_ID
"api_token": CROWDIN_PERSONAL_TOKEN
"base_path": ""
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/messages.xlf",
    "translation": "/locale/messages.%two_letters_code%.xlf"
  },
  {
    "source": "/messages.xlf",
    "translation": "/locale/messages.%two_letters_code%.xlf"
  }
]
