project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files: [
  {
    source: "messages.xlf",
    translation: "locale/messages.%two_letters_code%.xlf"
  },
  {
    source: "messages.xlf",
    translation: "locale/messages.%two_letters_code%.xlf"
  }
]

